### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by cxin-william** [keplergl/kepler.gl#2548] opened 2024-03-27 03:47 UTC
This hosting has been suspended
![Snipaste_2024-03-27_11-47-14](https://github.com/keplergl/kepler.gl/assets/66359848/7f40b035-9485-49cd-9f7a-ea66120ab1e5)

**Comment by ibgreen** [comment] 2024-03-27 15:24
Duplicate of #2551

**Closed by ibgreen** 2024-03-27 15:24 UTC
Labels: bug
