### ISSUE TITLE
[Bug] Custom Map Style loading failure

### ISSUE THREAD

**Issue by CalypsoR** [keplergl/kepler.gl#2560] opened 2024-04-11 13:05 UTC
**Describe the bug**
I am not able to load my Mapbox map style in Kepler.

**To Reproduce**
1. Go to 'Kepler.gl/demo'
2. Select 'Base Map' tab
3. Click on 'Add Map style'
4. Paste style URL 'mapbox://styles/leon-sildano/clrq8rugo001g01qvbzpudmn4' 
5. Add the name 'Locala map'  

**Expected behavior**
Add style button should be selectable.

**Screenshots**
<img width="2555" alt="Capture d’écran 2024-04-11 à 15 03 54" src="https://github.com/keplergl/kepler.gl/assets/166721281/59889bf1-a15c-45f4-9949-aa19af99a200">

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser Chrome
 - Version 123.0.6312.105 (Build officiel) (x86_64)

**Comment by akre54** [comment] 2024-04-18 20:53
Confirmed this is reproducible. Here's the stack trace with [this url](https://api.mapbox.com/styles/v1/examples/cjikt35x83t1z2rnxpdmjs7y7?access_token=pk.eyJ1Ijoic2lkZXdhbGstdXNlcnMiLCJhIjoiY2pnbnRyeXcwMGt6NDJxcjF4dDdzMDZpOSJ9.f17n6qwPPrk4z8yAP_-C0Q): 

```        
       Failed to load resource: net::ERR_FAILED
bundle.js:82 Error: Failed to fetch
    at bundle.js:19:128310
_onEvent @ bundle.js:82
bundle.js:419 Fetch API cannot load mapbox://mapbox.mapbox-streets-v7,examples.0fr72zt8. URL scheme "mapbox" is not supported.
(anonymous) @ bundle.js:419
bundle.js:419 Fetch API cannot load mapbox://sprites/examples/cjikt35x83t1z2rnxpdmjs7y7@2x.json. URL scheme "mapbox" is not supported.
(anonymous) @ bundle.js:419
bundle.js:419 Fetch API cannot load mapbox://sprites/examples/cjikt35x83t1z2rnxpdmjs7y7@2x.png. URL scheme "mapbox" is not supported.
(anonymous) @ bundle.js:419
3bundle.js:82 Error: Failed to fetch
    at bundle.js:19:128310
_onEvent @ bundle.js:82
```

**Comment by ibgreen** [comment] 2024-04-18 21:56
@ilyabo @birkskyum Some leftovers from the maplibre transition?

**Comment by birkskyum** [comment] 2024-04-18 22:01
The bug with the style button add style button not being clickable actually predates the work on maplibre transition.

This bug was i.e. reported here Nov 29, 2023:
- https://github.com/keplergl/kepler.gl/issues/2458

The maplibre transition PR merged and published Dec 19-21, 2023
- https://github.com/keplergl/kepler.gl/pull/2461

**Comment by akre54** [comment] 2024-04-19 01:23
Looks like the issue (or one issue) is that the `confirmButton` in the AddMapStyle modal is always disabled. It's checking for `mapStyle.inputStyle.style` which is always null since the input `onChange` listener only sets a `url` and not a `style` property. Also `addCustomMapStyleUpdater` is checking for `state.inputStyle.id` which is also null. 

Making these changes seems to help:

```diff
diff --git a/src/components/src/modal-container.tsx b/src/components/src/modal-container.tsx
index a26e7579..77152824 100644
--- a/src/components/src/modal-container.tsx
+++ b/src/components/src/modal-container.tsx
@@ -434,7 +434,7 @@ export default function ModalContainerFactory(
               onConfirm: this._onAddCustomMapStyle,
               confirmButton: {
                 large: true,
-                disabled: !mapStyle.inputStyle.style,
+                disabled: !mapStyle.inputStyle.url,
                 children: 'modal.button.addStyle'
               }
             };
diff --git a/src/components/src/modals/add-map-style-modal.tsx b/src/components/src/modals/add-map-style-modal.tsx
index f5e27343..72703488 100644
--- a/src/components/src/modals/add-map-style-modal.tsx
+++ b/src/components/src/modals/add-map-style-modal.tsx
@@ -194,7 +196,7 @@ function AddMapStyleModalFactory() {
                 <InputLight
                   type="text"
                   value={inputStyle.url || ''}
-                  onChange={({target: {value}}) => this.props.inputMapStyle({url: value})}
+                  onChange={({target: {value}}) => this.props.inputMapStyle({url: value, id: 'Custom Style
' })}
                   placeholder="e.g. https://basemaps.cartocdn.com/gl/positron-gl-style/style.json"
                 />
               </StyledModalSection>
```

Of course, the icon is broken, but this appears to be the basic fix.

**Comment by ibgreen** [comment] 2024-04-29 20:02
> It doesn't really make sense to continue supporting Mapbox  URLs unless the actual Mapbox library is added as an alternative option

Let's decide that we are going to remove the mapbox URL protocol. However, to avoid future confusion, we should do it right. 

There are a bunch of references to in docs and code to [mapbox:// url protocol](https://github.com/search?q=repo%3Akeplergl%2Fkepler.gl%20mapbox%3A%2F%2F&type=code). There could also be some screenshots.
If we no longer support it, that should be at least superficially cleaned up, in a quick PR.

> The functionality to load mapbox V1 styles works after a bugfix. I don't feel like having a preview icon is enough reason to break this workflow. What do you think?

If we can keep support for V1 styles that would be preferable, but I am still confused as to what is supported in maplibre and what is not.

**Comment by birkskyum** [comment] 2024-04-29 20:13
Any mapbox v1 style will still be supported by maplibre, albeit when passed as http://, not mapbox://, because there has yet to be introduced a breaking change in the style spec.

**Comment by akre54** [comment] 2024-04-29 20:30
So then it seems reasonable to not support `mapbox://` for base urls, and instead prefer http resources.

I've seen a few cases where assets *within* map style jsons are loaded via `mapbox://`, which might necessitate rewriting the urls or dropping support, but I think fixing the loading is probably enough for now. My preference would be for this to happen in maplibre but I understand if / why that's less than desirable. We can revisit if there's enough interest. Hows that sound?

**Comment by ph-kamil-galladzhov** [comment] 2024-09-16 18:49
> I've seen a few cases where assets within map style jsons are loaded via mapbox://

@akre54 that's exactly my case 😅 I have a base url defined as `https://api.mapbox.com/styles/v1/${MAPBOX_USER_ID}/${STYLE_ID}?access_token=${MAPBOX_TOKEN}`, but can't use it, since it uses `mapbox://` assets and I have a very limited control over it to be able to reconfigure styles. Is there anything I can do to help implementing this fix?

**Comment by sahitono** [comment] 2024-10-02 03:46
to be able use `mapbox://` in maplibre, can use request transformer like this https://github.com/rowanwins/maplibregl-mapbox-request-transformer

**Comment by akre54** [comment] 2024-10-02 07:04
Great find @sahitono. Would you be able to open a pull request?

**Comment by MoustafaWehbe** [comment] 2024-10-07 08:21
Any updates on this one? Are you going to open a PR that fixes it using `maplibregl-mapbox-request-transformer`?

**Comment by sahitono** [comment] 2024-10-14 03:42
Hi @akre54 , i just opened the PR #2693 but not sure where is the maplibre map initialize. would be helpful if maybe you can show me where is the maplibre map initialize

**Comment by akre54** [comment] 2024-10-14 04:48
Nice! Thanks for adding this.

What do you mean by the maplibre map initialize?

Kepler uses [react-map-gl](https://visgl.github.io/react-map-gl/) to construct the base maplib. If you need to call a function on load, for instance, you can use the [`onLoad` callback](https://visgl.github.io/react-map-gl/docs/api-reference/map#callbacks).

**Closed** 2024-12-13 18:36 UTC
Labels: bug
