### ISSUE TITLE
1. Go to Layersclick on new layer

### ISSUE THREAD

**Issue by XinyiHolly** [keplergl/kepler.gl#1086] opened 2020-04-17 02:01 UTC
**Describe the bug**

**To Reproduce**
1. Go to 'Layers'
2. Click on 'new layer'
3. Click on 'Data Source'
4. Cannot change the data source

**Expected behavior**
The data source can be changed by selecting from existing data files

**Screenshots**
![image](https://user-images.githubusercontent.com/25182813/79524316-cd04a380-8025-11ea-9f9a-d83b3f677f91.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 10

**Additional context**

**Comment by b2kdaman** [comment] 2020-04-17 08:21
Seen that bug too!

**Comment by macrigiuseppe** [comment] 2020-04-22 21:00
This is not an actual bug. This was created by design.

@b2kdaman @XinyiHolly currently you need to create a layer and map it against a different dataset

**Comment by XinyiHolly** [comment] 2020-04-29 01:01
Cool, but how can we map it against different datasets? I was describing
the problem there. When I tried to click on the dataset, it didn’t respond.
Where should I click instead?

**Comment by macrigiuseppe** [comment] 2020-04-29 17:12
@XinyiHolly as I mentioned before, you can't change the layer dataset once it was selected. You need to create a new layer and the reason to do so it's because of all properties and attributes of a given layer depend on the mapped dataset, if you were able to switch the current layer dataset you would have to start from scratch and fill out all properties again.

I am gonna close this one since this is not a bug

**Closed by macrigiuseppe** 2020-04-29 17:12 UTC
Labels: bug
