### ISSUE TITLE
[Bug] Importing data from a URL that's not a file no longer works

### ISSUE THREAD

**Issue by rjimenezda** [keplergl/kepler.gl#791] opened 2019-10-16 20:21 UTC
**Describe the bug**
Before #780, you could import data into kepler from APIs such as the CARTO SQL API, as long as the url ended in a recognized format. 

So, for instance, the URL`https://roman-carto.carto.com/api/v2/sql?q=select%20*%20from%20%22roman-carto%22.school_paths&format=geojson` would work nicely, because it ended in `geojson`. You can even specify `&filename=out.geojson`.

However, #780 introduced a new way of parsing the URI that is more restrictive.

**To Reproduce**
1. Go to kepler.gl/demo
2. Click on 'Load Map via URL'
3. Input `https://roman-carto.carto.com/api/v2/sql?q=select%20*%20from%20%22roman-carto%22.school_paths&format=geojson`
4. There'll be an error on the console because the file extension is not recognized.

**Expected behavior**
I would expect the data to be downloaded and imported.

**Comment by rjimenezda** [comment] 2019-10-16 20:23
I actually like the new approach to URL parsing, but maybe it should try to guess the file type if the URL parsing yielded nothing?

For instance, using the mime type of the response, or falling back to the previous approach.

**Comment by macrigiuseppe** [comment] 2019-11-01 16:30
@rjimenezda 
This is not a bug. The application is actually working as intended and the enhancement is required in order to pass extra params to an third party service when generating a file, e.g. /data.csv?start=[]&end=[]

We already have an open issue to automatically detect the type of file we are trying to dowload

https://github.com/keplergl/kepler.gl/issues/778

**Comment by VictorVelarde** [comment] 2019-11-04 12:01
Thx @macrigiuseppe! We'll be aware of the mime type change.

@rjimenezda could you please close this issue?

**Closed** 2019-11-06 06:45 UTC
Labels: bug
