### ISSUE TITLE
"Export map" flow feedback

### ISSUE THREAD

**Issue by chrisirhc** [keplergl/kepler.gl#446] opened 2019-03-18 21:44 UTC
Referring to https://github.com/uber/kepler.gl/blob/master/docs/user-guides/k-save-and-export.md#2export-current-map-as-html

- [ ] Shouldn't pre-fill this in the box, since this gives away our Mapbox token. It should be empty so users can fill it. We can pre-fill the value on the exported html if the user leaves the box empty
- [ ] Provide warning for the user that the map could stop working if they leave the Mapbox token blank (since it's using the example token).
- [ ] Links in "Export map" (e.g. Mapbox access token link, and How to update an existing map, and other links in export screens) should open in new window so as to not lose the map that the user is currently working on.

**Comment by macrigiuseppe** [comment] 2019-03-19 08:01
> Referring to https://github.com/uber/kepler.gl/blob/master/docs/user-guides/k-save-and-export.md#2export-current-map-as-html
> 
> * [ ]  Shouldn't pre-fill this in the box, since this gives away our Mapbox token. It should be empty so users can fill it. We can pre-fill the value on the exported html if the user leaves the box empty
> * [ ]  Provide warning for the user that the map could stop working if they leave the Mapbox token blank (since it's using the example token).
> * [ ]  Links in "Export map" (e.g. Mapbox access token link, and How to update an existing map, and other links in export screens) should open in new window so as to not lose the map that the user is currently working on.

- I feel if we don't pre-fill the token field people may think they require their token and would not export the map.
As far as security goes, since we are gonna export the token in the html anyway, we are not really improving the current state.

- We can definitely provide warning and messaging to users, i would wait on new design before making further changes.
- Links can definitely target a new tab/window.

**Comment by chrisirhc** [comment] 2019-03-19 16:04
> I feel if we don't pre-fill the token field people may think they require their token and would not export the map.
As far as security goes, since we are gonna export the token in the html anyway, we are not really improving the current state.
You can use placeholder text to indicate "leave blank to use the default".

When can these be fixed by? When would the new designs be ready? If they'll take long, we should consider making these quick changes.

**Comment by briantcl** [comment] 2019-03-19 17:00
I see both Giuseppe's and Chris's point. To my perspective (as someone who is not familiar with Mapbox token), I would prefer to have it pre-filled or ideally even skip this step since I am not familiar what a Mapbox token is and the afterward steps to obtain one. But at the same time, I see the concern that we don't want users to potentially abuse it.

Just some thoughts:
1) is there a way users can just directly export the html map file without dealing with token related matters? 
2) for security concerns, lets say if we embed the token in our flow, is there a way to not users to retrieve/ hash out the token so that users will not be able to extract the token?

> When can these be fixed by? When would the new designs be ready? If they'll take long, we should consider making these quick changes.

I will follow up with Stephanie today for the design. but to my perspective, this should not be blocked by her.

**Comment by macrigiuseppe** [comment] 2019-03-20 17:47
> I see both Giuseppe's and Chris's point. To my perspective (as someone who is not familiar with Mapbox token), I would prefer to have it pre-filled or ideally even skip this step since I am not familiar what a Mapbox token is and the afterward steps to obtain one. But at the same time, I see the concern that we don't want users to potentially abuse it.
> 
> Just some thoughts:
> 
> 1. is there a way users can just directly export the html map file without dealing with token related matters?
> 2. for security concerns, lets say if we embed the token in our flow, is there a way to not let users to retrieve/ hash out the token so that users will not be able to extract the token?
> 
> > When can these be fixed by? When would the new designs be ready? If they'll take long, we should consider making these quick changes.
> 
> I will follow up with Stephanie today for the design. but to my perspective, we should have these modified once we have the 'right' way to deal with the token. This should not be blocked by the new design. Thanks!

Answers:
1. The current flow was designed before we decided to provide one of our tokens to users. To answer your question, __yes we can skip the step and simply export the map into html__ but we need to communicate clearly with users how they can replace the given token with a new one because of the following scenarios
 - we rotate our token: the previous token is no longer valid and users must replace it with a new one provided by us (via our user guide link)
- users want to use their token
2. Unfortunately there is no way to hide tokens from users since we are dealing with a web app; especially the export map functionality generates an html file which is easy to read and update. See more info here: https://docs.mapbox.com/help/troubleshooting/how-to-use-mapbox-securely/

**Comment by macrigiuseppe** [comment] 2019-04-01 22:05
Actions items:
- Remove pre-filled token from UI
- Remove link from "Please provide your Mapbox access token"
- the link target for docs should be _blank

**Comment by heshan0131** [comment] 2019-04-02 23:06
Update on this thread after today's meeting with mapbox

- User shouldn't be forced to enter a token for the exported map to work
- We will provide a token for exported map, but rotate it every month. This means if they don't enter a token, the map will break after a while.
- We will let the user know that `We will provide a temporary token, If you don't provide your own token, map will break. You can later follow this instruction to edit html and input token`

- Adding clear instruction on how to edit the `html file` and replace token with their own for the expired map to work.

**Comment by macrigiuseppe** [comment] 2019-04-03 03:59
Updated pull request accordingly: https://github.com/uber/kepler.gl/pull/463

**Comment by briantcl** [comment] 2019-04-05 18:08
pending review

**Comment by macrigiuseppe** [comment] 2019-05-06 01:49
Closing because implemented in #482

**Closed by macrigiuseppe** 2019-05-06 01:49 UTC
Labels: internal
