### ISSUE TITLE
[Bug] Cloud provider authentication errors doesn't clear after login

### ISSUE THREAD

**Issue by neokore** [keplergl/kepler.gl#998] opened 2020-03-10 16:21 UTC
**Describe the bug**
When an authentication error appears, it doesn't clear after authentication is fixed.

**To Reproduce**
1. Go to "Add Data".
2. Go to "Try sample Data".
3. Load any sample map.
4. When loaded, go to "Cloud Storage" > "Save".
5. Fill the name field.
6. Click on the "Save button".
7. An authentication error message should appear.
8. Select and login with any cloud provider using the "Cloud Storage" boxes above.
9. After login, the authentication error remains on screen.

**Expected behavior**
After loging in, the authentication error must disappear.

**Comment by macrigiuseppe** [comment] 2020-03-10 18:07
this is duplicate of #990

**Comment by macrigiuseppe** [comment] 2020-03-13 18:04
fixed

**Closed by macrigiuseppe** 2020-03-13 18:04 UTC
Labels: bug
