### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by jordanbell2357** [keplergl/kepler.gl#2185] opened 2023-04-01 05:56 UTC
**Describe the bug**

Fluttering Chrome screen. 

https://www.operations.amsa.gov.au/Spatial/DataServices/DigitalData

Converted shapefile to CSV (January 2020). `cts_srr_01_2020_pt.shp` (and associated files) to `cts_srr_01_2020_pt.csv`. CSV is 211MB. Viewable in QGIS.

Also, in between the fluttering screen, nothing happens clicking image export.

I've tried using kepler.gl several times; all the datasets I have are at least in the 100s of MB, and I've had similar results every time. I've never been able to export an image (trying in Edge and Firefox also with no popup blocking). I presume the issue is with the size of the datasets I'm trying to use the platform for, and that the export would work for small datasets.  

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by chrisgervang** [comment] 2023-10-18 18:02
If this issue was caused by the image export feature, I believe this is fixed now with #2368. Try `3.0.0-alpha.1`

**Comment by chrisgervang** [comment] 2024-05-19 00:25
Closing inactive issue that appears fixed. Please reopen if the issue is not fixed.

**Closed by chrisgervang** 2024-05-19 00:25 UTC
Labels: bug
