### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by dbnezami** [keplergl/kepler.gl#2204] opened 2023-04-20 17:33 UTC
**Describe the bug**
Image download button does nothing

**To Reproduce**
Create a custom map with a custom dataset, attempt to download image of map

**Expected behavior**
A downloadable image of the map

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RaineEkman** [comment] 2023-06-01 06:56
Duplicate of https://github.com/keplergl/kepler.gl/issues/1960?

**Comment by chrisgervang** [comment] 2023-10-18 17:58
I believe this is fixed now with #2368. Try `3.0.0-alpha.1`

**Closed as completed** 2024-12-05 05:54 UTC
Labels: bug
