### ISSUE TITLE
[Bug] Map exporting not working on 3.0.0-alpha.0

### ISSUE THREAD

**Issue by mavezum-vay** [keplergl/kepler.gl#2033] opened 2022-11-18 16:52 UTC
**Describe the bug**

**To Reproduce**
1. Add several dta sources to a map
2. Add a custom  base layer
3. Try exporting the map, with the base layer and mapbox access token. Allow users to edit the map
4.  Download the exported map 
5. Open the exported map
6. Map doesn't load

**Expected behavior**
The exported map should be identical to the one visualised in Kepler, but it does not load

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Mac OS Monterey
 - Browser  Chrome
 - Version Chrome v105

**Additional context**

**Comment by jlondonob** [comment] 2022-11-25 14:26
This might be a duplicate of #2028

**Closed as completed** 2024-12-05 06:00 UTC
Labels: bug
