### ISSUE TITLE
[Bug] - Export to Image Download is not working.

### ISSUE THREAD

**Issue by Finrootz** [keplergl/kepler.gl#2227] opened 2023-05-17 17:30 UTC
Export to Image is not working.
While doing Export to Image and Download the UI is stuck and not able to download the image.

1. Please navigate https://[kepler.gl](https://kepler.gl/demo)/demo website.
2. Click Share Icon from Side Panel.
3. Click Export to Image.
4. once the example Image is rendered, please click Download button.

The UI will be stuck. and from inspect console you will be able to see below provided error.
![image](https://github.com/keplergl/kepler.gl/assets/132917969/ea8b78da-2a15-43e6-9f20-7beae65017c1)

**Expected behavior**
The Export to Image Download button should download an image.

**Additional context**
Kepler.gl version - 3.0.0-alpha.0

**Comment by RaineEkman** [comment] 2023-06-01 06:55
Duplicate of https://github.com/keplergl/kepler.gl/issues/1960?

**Closed as completed** 2024-12-05 05:20 UTC
Labels: bug
